### ISSUE TITLE
Remove unwanted npm dependencies 

### ISSUE THREAD

**Issue by Harshil-Jani** [Samagra-Development/generator-create-rc-admin#3]
We got lots of unwanted dependencies in our [general purpose admin](https://github.com/Samagra-Development/generator-create-rc-admin/tree/main/generators/app/templates/general-admin). The task is to clean them up and have good logs with least warnings possible.

**Comment by void-ness** [comment]
Hey, I went through the package.json file for the same. I can spot the "i" dependency which I sense is unwanted. I don't see any imports for the concerned module in the general purpose admin project. Are there any other unwanted dependencies that I should look for? 

![image](https://user-images.githubusercontent.com/78547746/187033950-85099bd3-8d67-4503-91dc-7eec0229e6b7.png)

**Comment by Harshil-Jani** [comment]
@void-ness  Maybe , You can try generating the general admin and go through the warning logs and upgrade the dependencies, Remove which are not required. I guess `i` and testing libs are the ones which we don;t need. You can play around with the package config as per the warnings recieved while building up the general admin.

**Comment by void-ness** [comment]
Sure, I will consider that. Can you assign this issue to me. Thanks
